import { Bitter, Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import "./globalicon.css";

const inter = Inter({ subsets: ["latin"] });
const bitter = Bitter({ subsets: ["latin"] });
const roboto= Roboto_Condensed({subsets:["latin"]})
export const metadata = {
  title: "William Ziller - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
