import { Bitter, Inter } from "next/font/google";
import "./globals.css";
import "./globalicon.css";

const inter = Inter({ subsets: ["latin"] });
const bitter = Bitter({ subsets: ["latin"] });
export const metadata = {
  title: "William Ziller - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bitter.className}>{children}</body>
    </html>
  );
}
